Stellarium/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Stellarium.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string? ExceptionMessage { get; set; }

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;

            var exceptionHandlerPathFeature =
    HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            if (exceptionHandlerPathFeature?.Error is FileNotFoundException)
            {
                ExceptionMessage = "The file was not found.";
            }

            if (exceptionHandlerPathFeature?.Path == "/")
            {
                ExceptionMessage ??= string.Empty;
                ExceptionMessage += " Page: Home.";
            }
        }
    }
}

Stellarium/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Stellarium.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Stellarium/Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stellarium.Models;

namespace Stellarium.Pages
{
    public class ProfileModel : PageModel
    {
        public ApplicationContext Context;
        public User User;
        public string RegDate;
        public string LastOnline;
        public List<PublicationV2> Publications = new List<PublicationV2>();
        public User CurrentUser;
        public List<BookMark> UserBookmarks = new List<BookMark>();
        public ProfileModel(ApplicationContext db)
        {
            Context = db;
        }

        public void OnGet(int id)
        {
            try
            {
                User = Context.Users.FirstOrDefault(u => u.Id == id);
                RegDate = User.RegistrationDate.ToString("dd MMMM yyyy");
                LastOnline = Entity.OverDay(User.LastOnline);
            }
            catch 
            {
                return;
            }


            string useremail = Request.Cookies["useremail"];
            if (useremail != null)
            {
                CurrentUser = Context.Users.FirstOrDefault(x => x.Email == useremail);
                UserBookmarks = Context.Bookmarks.Where(b => b.UserId == CurrentUser.Id).ToList();
            }
            RefreshOutput();
        }

        void RefreshOutput()
        {
            Publications.Clear();
            foreach (var publication in Context.Publications.Where(p => p.UserId == User.Id && p.IsPublicated == true).OrderByDescending(p => p.DateTime))
            {
                var views = Context.Views.Where(v => v.PublicationId == publication.Id).Count();
                var comments = Context.Comments.Where(c => c.PublicationId == publication.Id).Count();
                var publicationCategories = Context.PublicationCategories.Where(c => c.PublicationId == publication.Id).ToList();
                List<Category> Categories = new List<Category>();
                foreach (var publicationCategory in publicationCategories)
                {
                    Categories.Add(Context.Categories.FirstOrDefault(c => c.Id == publicationCategory.CategoryId));
                }
                Publications.Add(new PublicationV2(publication, User, views, comments, Categories.ToList()));
            }
        }

        public async void OnPostAddBookMark(int userid, int id)
        {
            try
            {
                OnGet(userid);
                var newBookmark = new BookMark(0, CurrentUser.Id, id);
                if (!Context.Bookmarks.Contains(newBookmark))
                {
                    Context.Bookmarks.Add(newBookmark);
                    Context.SaveChanges();
                    UserBookmarks.Add(newBookmark);
                    RefreshOutput();
                }
            }
            catch
            {
            }
        }

        public async void OnPostDeleteBookMark(int userid, int id)
        {
            try
            {
                OnGet(userid);
                var bookmark = Context.Bookmarks.FirstOrDefault(b => b.UserId == CurrentUser.Id && b.PublicationId == id);
                Context.Bookmarks.Remove(bookmark);
                Context.SaveChanges();
                UserBookmarks.Remove(bookmark);
                RefreshOutput();
            }
            catch
            {
            }
        }
    }
}

Stellarium/Pages/Publication.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stellarium.Models;
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Stellarium.Pages
{
    public class PublicationModel : PageModel
    {
        public ApplicationContext Context;
        public PublicationV2 Publication;
        public List<CommentV2> Comments = new List<CommentV2>();
        public User CurrentUser;
        public BookMark UserBookmark;
        public PublicationModel(ApplicationContext db)
        {
            Context = db;
        }

        public async void OnGet(int id)
        {
            await GetPublication(id);
        }

        public async void OnPostSendComment(int id, string text)
        {
            if (text == null)
            {
                return;
            }
            await GetPublication(id);
            var newComment = new Comment(0, CurrentUser.Id, Publication.Publication.Id, text, null, DateTime.Now);
            Context.Comments.Add(newComment);
            var newCommentV2 = new CommentV2(newComment, Context.Users.FirstOrDefault(u => u.Id == newComment.UserId), newComment.Date, Context.Comments.FirstOrDefault(c => c.Id == newComment.AnswerOnId));
            if (Comments.FirstOrDefault(c => c.Comment.Text == text && c.User == CurrentUser) == null)
            {
                Comments.Add(newCommentV2);
                Publication.Comments++;
                CurrentUser.Score += 3;
                Context.SaveChanges();
            }
            else
            {
                ViewData["Message"] = "true";
            }
        }

        public async void OnPostDeleteComment(int id, int commentId)
        {
            await GetPublication(id);
            var comment = Context.Comments.FirstOrDefault(c => c.Id == commentId);
            if (comment != null)
            {
                var answers = Context.Comments.Where(c => c.AnswerOnId == commentId);
                if (answers != null)
                {
                    foreach (var answer in answers)
                    {
                        Context.Comments.Remove(answer);
                    }
                }
                Context.Comments.Remove(comment);
                CurrentUser.Score -= 3;
                Context.SaveChanges();
                Comments.Remove(Comments.FirstOrDefault(c => c.Comment == comment));
                Publication.Comments--;
            }
        }

        async Task GetPublication(int id)
        {
            var publication = Context.Publications.FirstOrDefault(p => p.Id == id);
            var vid = HttpUtility.UrlDecode(Request.Cookies["visitorId"]);
            int visitorId = Convert.ToInt32(vid);
            if (Context.Views.FirstOrDefault(v => v.VisitorId == visitorId && v.PublicationId == publication.Id) == null)
            {
                Context.Views.Add(new View(0, visitorId, publication.Id));
                Context.SaveChanges();
            }

            var users = Context.Users.ToList();
            var user = users.FirstOrDefault(u => u.Id == publication.UserId);
            var views = Context.Views.Where(v => v.PublicationId == publication.Id).Count();
            foreach (var comment in Context.Comments.Where(c => c.PublicationId == publication.Id).ToList())
            {
                Comments.Add(new CommentV2(comment, Context.Users.FirstOrDefault(u => u.Id == comment.UserId), comment.Date, Context.Comments.FirstOrDefault(c => c.Id == comment.AnswerOnId)));
            }
            List<Category> Categories = new List<Category>();
            var publicationCategories = Context.PublicationCategories.Where(c => c.PublicationId == publication.Id).ToList();
            foreach (var publicationCategory in publicationCategories)
            {
                Categories.Add(Context.Categories.FirstOrDefault(c => c.Id == publicationCategory.CategoryId));
            }
            Publication = new PublicationV2(publication, user, views, Comments.Count(), Categories);

            string useremail = Request.Cookies["useremail"];
            if (useremail != null)
            {
                CurrentUser = Context.Users.FirstOrDefault(x => x.Email == useremail);
                UserBookmark = Context.Bookmarks.FirstOrDefault(b => b.UserId == CurrentUser.Id && b.PublicationId == Publication.Publication.Id);
            }

        }
        public async void OnPostAddBookMark(int id)
        {
            try
            {
                await GetPublication(id);
                UserBookmark = new BookMark(0, CurrentUser.Id, Publication.Publication.Id);
                if (!Context.Bookmarks.Contains(UserBookmark))
                {
                    Context.Bookmarks.Add(UserBookmark);
                    Context.SaveChanges();
                }
            }
            catch 
            {
            }
        }

        public async void OnPostDeleteBookMark(int id)
        {
            try
            {
                await GetPublication(id);
                Context.Bookmarks.Remove(UserBookmark);
                Context.SaveChanges();
                UserBookmark = null;
            }
            catch
            {
            }
        }

        [BindProperty]
        public BufferedMessage Message { get; set; }

        public class BufferedMessage
        {
            [Required]
            [Display(Name = "Message")]
            public string MessageText { get; set; }
        }

        public async void OnPostAnswer(int id, int commentId, string answerText2)
        {
            await GetPublication(id);
            if (answerText2 == null || answerText2 == "null")
            {
                return;
            }
            var newComment = new Comment(0, CurrentUser.Id, Publication.Publication.Id, answerText2, commentId, DateTime.Now);
            Context.Comments.Add(newComment);
            var newCommentV2 = new CommentV2(newComment, Context.Users.FirstOrDefault(u => u.Id == newComment.UserId), newComment.Date, Context.Comments.FirstOrDefault(c => c.Id == newComment.AnswerOnId));
            if (Comments.FirstOrDefault(c => c.Comment.Text == answerText2 && c.User == CurrentUser) == null)
            {
                Comments.Add(newCommentV2);
                Publication.Comments++;
                Context.SaveChanges();
            }
            else
            {
                ViewData["Message"] = "true";
            }
        }
    }
}

Stellarium/Pages/RulesAndGuides.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Stellarium.Pages
{
    public class RulesAndGuidesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Stellarium/Pages/Scoreboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stellarium.Models;

namespace Stellarium.Pages
{
    public class ScoreboardModel : PageModel
    {
        ApplicationContext Context;
        public List<User> Users { get; set; }
        public ScoreboardModel(ApplicationContext db)
        {
            Context = db;
        }
        public void OnGet()
        {
            Users = Context.Users.Where(u => u.Score > 0).OrderByDescending(u => u.Score).ToList();
        }
    }
}

Stellarium/Pages/Unpublished.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stellarium.Models;

namespace Stellarium.Pages
{
    public class UnpublishedModel : PageModel
    {
        ApplicationContext Context;
        public List<PublicationV2> Publications = new List<PublicationV2>();

        public UnpublishedModel(ApplicationContext db)
        {
            Context = db;
        }

        public void OnGet()
        {
            Publications.Clear();
            var users = Context.Users.ToList();
            List<Category> Categories = new List<Category>();
            foreach (var publication in Context.Publications.Where(p => p.IsPublicated == false).OrderByDescending(p => p.DateTime))
            {
                var user = users.FirstOrDefault(u => u.Id == publication.UserId);
                var views = Context.Views.Where(v => v.PublicationId == publication.Id).Count();
                var comments = Context.Comments.Where(c => c.PublicationId == publication.Id).Count();
                var publicationCategories = Context.PublicationCategories.Where(c => c.PublicationId == publication.Id).ToList();
                foreach (var publicationCategory in publicationCategories)
                {
                    Categories.Add(Context.Categories.FirstOrDefault(c => c.Id == publicationCategory.CategoryId));
                }
                Publications.Add(new PublicationV2(publication, user, views, comments, Categories.ToList()));
                Categories.Clear();
            }
        }
    }
}

Stellarium/Pages/UnpublishedPublication.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stellarium.Models;

namespace Stellarium.Pages
{
    public class UnpublishedPublicationModel : PageModel
    {
        public ApplicationContext Context;
        public PublicationV2 Publication;
        public List<CommentV2> Comments = new List<CommentV2>();
        public User User;
        public UnpublishedPublicationModel(ApplicationContext db)
        {
            Context = db;
        }

        public async void OnGet(int id)
        {
            GetPublication(id);
        }

        public void OnPostPublicate(int id)
        {
            GetPublication(id);
            Publication publication = Context.Publications.FirstOrDefault(p => p.Id == id);
            publication.IsPublicated = true;
            publication.DateTime = DateTime.Now;
            Context.Publications.Update(publication);
            User.Score += 25;
            Context.SaveChanges();
            RedirectToPage("/Unpublished");
        }

        public void GetPublication(int id)
        {
            var publication = Context.Publications.FirstOrDefault(p => p.Id == id);
            var users = Context.Users.ToList();
            var user = User = users.FirstOrDefault(u => u.Id == publication.UserId);
            var views = Context.Views.Where(v => v.PublicationId == publication.Id).Count();
            foreach (var comment in Context.Comments.Where(c => c.PublicationId == publication.Id).ToList())
            {
                Comments.Add(new CommentV2(comment, Context.Users.FirstOrDefault(u => u.Id == comment.UserId), comment.Date, Context.Comments.FirstOrDefault(c => c.Id == comment.AnswerOnId)));
            }
            List<Category> Categories = new List<Category>();
            var publicationCategories = Context.PublicationCategories.Where(c => c.PublicationId == publication.Id).ToList();
            foreach (var publicationCategory in publicationCategories)
            {
                Categories.Add(Context.Categories.FirstOrDefault(c => c.Id == publicationCategory.CategoryId));
            }
            Publication = new PublicationV2(publication, user, views, Comments.Count(), Categories);
        }

        public void OnPostDelete(int id)
        {
            GetPublication(id);
            var publication = Context.Publications.FirstOrDefault(p => p.Id == id);
            try
            {
                for (int i = 0; i < 100; i++)
                {
                    Context.PublicationCategories.Remove(Context.PublicationCategories.FirstOrDefault(pc => pc.PublicationId == id));
                }
                for (int i = 0; i < 100; i++)
                {
                    Context.Views.Remove(Context.Views.FirstOrDefault(v => v.PublicationId == id));
                }
                for (int i = 0; i < 100; i++)
                {
                    Context.Comments.Remove(Context.Comments.FirstOrDefault(c => c.PublicationId == id));
                }
            }
            catch 
            {
            }
            try
            {

                Context.SaveChanges();
                Context.Publications.Remove(publication);
                Context.SaveChanges();
            }
            catch
            {
            }
            RedirectToPage("/Unpublished");
        }
    }
}

Stellarium/Pages/Auth.cshtml
@page
@model Stellarium.Pages.AuthModel
@{
	Layout = null;
	<meta name="google-signin-client_id" content="564844095411-3nfvcdjnaj26u0qj1kkifi4849i3n6pl.apps.googleusercontent.com">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Stellarium.styles.css" asp-append-version="true" />
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://apis.google.com/js/platform.js" async defer></script>
	<title>Авторизация - Stellarium</title>

	<body onload="OnLoadAuth()">

	<div class="loginform" style="text-align:center">
	<a style="margin:10px; height:50px; position:relative; bottom:20px; " asp-area="" asp-page="/Index"> <img class="icon"/></a>
		<form method="post" asp-page-handler="Authorise" id="form" style="text-align:center">
			<a id="text" asp-page="/Index">@Model.Username</a><br>
			<button style="position:relative; left:-10px;" class="g-signin2" data-onsuccess="onSignIn">войти</button><br>
		</form>
		<a href="#" onclick="signOut();">Выход</a>
	</div>

	</body>

	<script>
	  function signOut() {
		var auth2 = gapi.auth2.getAuthInstance();
		auth2.signOut().then(function () {
			console.log('User signed out.');
			document.cookie = "username=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
			document.cookie = "useremail=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
			document.cookie = "userimg=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
			document.cookie = "userid=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
			document.cookie = "ismoderator=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
			window.localStorage.removeItem('username', null);
			window.localStorage.removeItem('userimg', null);
			window.localStorage.removeItem('useremail', null);
			window.localStorage.removeItem('userid', null);
			location.reload();
		});
	  }
	</script>
}

Stellarium/Pages/Profile.cshtml
@page
@model Stellarium.Pages.ProfileModel
@{
	 ViewData["Title"] = "Профиль - " + @Model.User.Name.Replace('_', ' ');
	 <div class="profile">
		 <div class="profileheader">
            <div style="width:70px; position:relative; right:15px">
	 		<img style="width:70px" src="@Model.User.Icon">
            </div>

            <div style=" position:relative; bottom:80px; left:60px">
            <span class="userspan">@Model.User.Name.Replace('_', ' ')</span><span class="userspan"> Рейтинг = @Model.User.Score</span>
            @if (Model.CurrentUser == Model.User)
            {
                    <a style="bottom:-2px;" asp-page="/Auth" class="loginuser" id="login">Выход</a>
            }
            else
            {
                <a style="color:orange" href="mailto: @Model.User.Email">@Model.User.Email</a>
            }
            <br>
			<span class="userspan">Дата регистрации: @Model.RegDate</span><br>
			<span class="userspan">Был(а) онлайн: @Model.LastOnline</span><br>
            </div>
		 </div>
	 </div>

     <div class="publicationsprofile">
	 @foreach (var publication in @Model.Publications)
     {
        <div class="publication">
            <img class="authorimg" src="@publication.User.Icon"><span class="userspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@publication.User.Id">@publication.User.Name.Replace('_', ' ')</a></span><span class="userspan">@publication.Date</span><br>
            <h3 class="title"><a class="pba" asp-route-id="@publication.Publication.Id" asp-page="/Publication">@publication.Publication.Title</a>
            </h3>
            <br>
            <div class="categories">
                @for (var i = 0; i < @publication.Categories.Count; i++)
                {
                    <a asp-page="/Index" asp-route-section="@publication.Categories[i].Name">@publication.Categories[i].Name</a>
                    if (i < @publication.Categories.Count-1)
                    {
                        @Html.Raw(" | ")
                    }
                }
            </div>
            <span class="titletext">@publication.Publication.TitleText</span><br>
            <img class="pbimg" src="@publication.Publication.Image"><br>
            <i class="fa-solid fa-eye"></i> @publication.Views <i class="fa-solid fa-message"></i> @publication.Comments
            @if (@Model.UserBookmarks.FirstOrDefault(b => b.PublicationId == publication.Publication.Id) == null)
            {
                <form class="bookmarlform" method="post" asp-page-handler="AddBookMark" asp-route-userid="@Model.User.Id" asp-route-id="@publication.Publication.Id">
                    <button class="bookmarkouter" title="Добавить в избранное"><i class="fa-solid fa-bookmark"></i></button>
                </form>
            }
            else
            {
                <form class="bookmarlform" method="post" asp-page-handler="DeleteBookMark" asp-route-userid="@Model.User.Id" asp-route-id="@publication.Publication.Id">
                    <button class="bookmarkouter" title="Удалить из избранного"><i class="fa-regular fa-bookmark"> </i></button>
                </form>
            }
            <br />
        </div>
        }
        </div>
}

Stellarium/Pages/Publication.cshtml
@page
@model Stellarium.Pages.PublicationModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = @Model.Publication.Publication.Title;
	<div class="innerpublication">
        <img class="authorimg" src="@Model.Publication.User.Icon"><span class="userspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@Model.Publication.User.Id">@Model.Publication.User.Name.Replace('_', ' ')</a></span>
            <div style="display:inline; top:2px" class="categories">
                @for (var i = 0; i < @Model.Publication.Categories.Count; i++)
                {
                    <a asp-page="/Index" asp-route-section="@Model.Publication.Categories[i].Name">@Model.Publication.Categories[i].Name</a>
                    if (i < @Model.Publication.Categories.Count-1)
                    {
                        @Html.Raw(" | ")
                    }
                }
            </div>
        <span class="userspan">@Model.Publication.Date</span><span class="userspan"><i class="fa-solid fa-eye fa-sm"></i> @Model.Publication.Views</span><br>
        <h1 class="title">@Model.Publication.Publication.Title</h1>
        @if (@Model.UserBookmark == null)
        {
            <form class="bookmarlform" method="post" asp-page-handler="AddBookMark" asp-route-id="@Model.Publication.Publication.Id">
                <button class="bookmark" title="Добавить в избранное"><i class="fa-solid fa-bookmark"></i></button>
            </form>
        }
        else
        {
            <form class="bookmarlform" method="post" asp-page-handler="DeleteBookMark" asp-route-id="@Model.Publication.Publication.Id">
                <button class="bookmark" title="Удалить из избранного"><i class="fa-regular fa-bookmark"> </i></button>
            </form>
        }
        <span class="ptext">
            @Html.Raw(@Model.Publication.Publication.Text)
        </span>
        <hr>
        @if (@Model.CurrentUser != null)
        {
            <form asp-page-handler="SendComment" method="post" asp-route-id="@Model.Publication.Publication.Id" enctype="multipart/form-data">
            <img class="commentauthor1" width="50px" src="@Model.CurrentUser.Icon">
            <textarea asp-for="Message.MessageText" placeholder="Оставить комментарий" type="text" class="inputcomment" name="text" onKeyUp="MessageText()" id="messageText"></textarea>
            <br>
                <button>Оставить комментарий</button>
                @if (ViewData["Message"] != null)
                {
                    <div>Вы уже оставили такой комментарий</div>
                }
            </form>
        }
        else
        {
            <br />
            <a asp-page="/Auth" class="loginuser">Авторизуйтесь для комментирования</a>
            <br />
        }
        Всего @Model.Publication.Comments @Model.Publication.CommentsString
        <hr>
        <div class="comments">
            @foreach (var comment in @Model.Comments.Where(c => c.AnsverAt == null).ToList())
            {
                <div class="comment">
                    <img src="@comment.User.Icon" class="commentauthor" width="50px"> <span class="commentuserspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@comment.User.Id">@comment.User.Name.Replace('_', ' ')</a> @comment.Date
                    <form method="post" asp-page-handler="Answer" asp-route-id="@Model.Publication.Publication.Id" style="display:inline" enctype="multipart/form-data">
                        <button style="color:orange; border:none"><i style="transform:scaleX(-1)" class="fa-solid fa-share"></i> Ответить</button>
                        <input name="commentId" type="hidden" value="@comment.Comment.Id">
                        <input id="answerText" name="answerText2" type="hidden" value="null">
                    </form>
                    @if (comment.User == Model.CurrentUser)
                    {
                        <form class="commentcrossform" method="post" asp-page-handler="DeleteComment" asp-route-id="@Model.Publication.Publication.Id">
                            <button class="cross"><i class="fa-solid fa-xmark"></i></button>
                            <input name="commentId" type="hidden" value="@comment.Comment.Id">
                        </form>
                    }
                    @if (comment.User == Model.Publication.User)
                    {
                        <div style="display:inline; background-color: DarkCyan; border-radius:5px;">Автор</div>
                    }
                    </span>
                    <br>
                    <span class="commenttext">@Html.Raw(@comment.Comment.Text)</span>
                    <div style="position:relative; left:30px">
                        @foreach (var comment2 in @Model.Comments.ToList())
                        {
                            @if (comment2.AnsverAt != null)
                            {
                                @if (comment2.AnsverAt.Id == comment.Comment.Id)
                                {
                                <div class="comment">
                                    <img src="@comment2.User.Icon" class="commentauthor" width="50px"> <span class="commentuserspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@comment2.User.Id">@comment2.User.Name.Replace('_', ' ')</a> @comment2.Date
                                    @if (comment2.User == Model.CurrentUser)
                                    {
                                        <form class="commentcrossform" method="post" asp-page-handler="DeleteComment" asp-route-id="@Model.Publication.Publication.Id">
                                            <button class="cross"><i class="fa-solid fa-xmark"></i></button>
                                            <input name="commentId" type="hidden" value="@comment2.Comment.Id">
                                        </form>
                                    }
                                    @if (comment2.User == Model.Publication.User)
                                    {
                                        <div style="display:inline; background-color: DarkCyan; border-radius:5px;">Автор</div>
                                    }
                                    </span>
                                    <br>
                                    <span class="commenttext">@Html.Raw(@comment2.Comment.Text)</span>
                                </div>
                                }
                            }
                        }
                    </div>
                </div>
            }
        </div>
        <br />
    </div>
}

Stellarium/Pages/Scoreboard.cshtml
@page
@model Stellarium.Pages.ScoreboardModel
@{
	ViewData["Title"] = "Рейтинг пользователей";
}
<div class="scoreboard">
	<h2 style="margin-right:330px">Рейтинг пользователей</h2>
	<table style="margin-right:330px">
		<tr><th width="75px" class="scoreth"><h3>Позиция</h3></th><th width="200px" class="scoreth"><h3>Пользователь</h3></th><th width="75px" class="scoreth"><h3>Рейтинг</h3></th></tr>

		@for (int i = 0; @Model.Users.Count > i; i++)
		{
			<tr><td>@(i+1)</td><td><img class="authorimg" src="@Model.Users[i].Icon"><span class="userspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@Model.Users[i].Id">@Model.Users[i].Name</a></span></td><td>@Model.Users[i].Score</td></tr>
		}
	</table>
</div>

Stellarium/Pages/UnpublishedPublication.cshtml
@page
@model Stellarium.Pages.UnpublishedPublicationModel
@{
ViewData["Title"] = @Model.Publication.Publication.Title;
    <div class="innerpublication">
        <img class="authorimg" src="@Model.Publication.User.Icon"><span class="userspan"><a style="color:orange" asp-page="/Profile" asp-route-id="@Model.Publication.User.Id">@Model.Publication.User.Name.Replace('_', ' ')</a> <a style="color:orange" href="mailto: @Model.Publication.User.Email">@Model.Publication.User.Email</a></span><br>
            <div style="display:inline; top:2px" class="categories">
                @for (var i = 0; i < @Model.Publication.Categories.Count; i++)
                {
                    <a asp-page="/Index" asp-route-section="@Model.Publication.Categories[i].Name">@Model.Publication.Categories[i].Name</a>
                    if (i < @Model.Publication.Categories.Count-1)
                    {
                        @Html.Raw(" | ")
                    }
                }
            </div><br>
        <h1 class="title">@Model.Publication.Publication.Title</h1>
        <span class="ptext">
            @Html.Raw(@Model.Publication.Publication.Text)
        </span>
        <form asp-page-handler="Publicate" method="post" asp-route-id="@Model.Publication.Publication.Id" style="display:inline">
                <button style="display:inline">Одобрить и опубликовать</button>
        </form>
        <form asp-page-handler="Delete" method="post" asp-route-id="@Model.Publication.Publication.Id" style="display:inline">
            <button style="display:inline">Удалить</button>
        </form>
    </div>
}